// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/devendrapratap307/go-crypto-service/internal/config"
	"github.com/devendrapratap307/go-crypto-service/internal/handler"
	"github.com/devendrapratap307/go-crypto-service/internal/keys"
	"github.com/devendrapratap307/go-crypto-service/internal/service"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	keyManager, err := keys.NewKeyManager(configConfig)
	if err != nil {
		return nil, err
	}
	cryptoService := service.NewCryptoService(keyManager)
	restHandler := handler.NewRestHandler(cryptoService)
	grpcServer := handler.NewGRPCServer(cryptoService)
	app := NewApp(restHandler, grpcServer)
	return app, nil
}

// wire.go:

type App struct {
	RestHandler *handler.RestHandler
	GRPCServer  *handler.GRPCServer
}

func NewApp(rest *handler.RestHandler, grpc *handler.GRPCServer) *App {
	return &App{RestHandler: rest, GRPCServer: grpc}
}
